function lng() {
  var elementA = document.getElementById("hiA");
  var elementB = document.getElementById("enA");
  var elementC = document.getElementById("hiB");
  var elementD = document.getElementById("enB");
  var elementE = document.getElementById("hiC");
  var elementF = document.getElementById("enC");
  var element1 = document.getElementById("hi0");
  var element2 = document.getElementById("en0");
  var element3 = document.getElementById("hi1");
  var element4 = document.getElementById("en1");
  var element5 = document.getElementById("hi2");
  var element6 = document.getElementById("en2");
  var element7 = document.getElementById("hi3");
  var element8 = document.getElementById("en3");
  var element9 = document.getElementById("hi4");
  var element10 = document.getElementById("en4");
  elementA.classList.toggle("hide");
  elementB.classList.toggle("hide");
  elementC.classList.toggle("hide");
  elementD.classList.toggle("hide");
  elementE.classList.toggle("hide");
  elementF.classList.toggle("hide");
  element1.classList.toggle("hide");
  element2.classList.toggle("hide");
  element3.classList.toggle("hide");
  element4.classList.toggle("hide");
  element5.classList.toggle("hide");
  element6.classList.toggle("hide");
  element7.classList.toggle("hide");
  element8.classList.toggle("hide");
  element9.classList.toggle("hide");
  element10.classList.toggle("hide");
}